"""
Optional: renders the Markdown policy documents (generated by
data/synthetic/generators/documents.py) into PDF, using `reportlab` if it's
installed. This is purely cosmetic for the "Document Intelligence" demo
(AI_PARSE_DOCUMENT expects a PDF in the original design) — the RAG pipeline
works fine ingesting the .md files directly if you skip this step.

Usage:
    pip install reportlab
    python data/documents/render.py
"""
from __future__ import annotations

import sys
from pathlib import Path

DOCS_DIR = Path(__file__).parent


def render_pdf(md_path: Path, pdf_path: Path) -> None:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(str(pdf_path), pagesize=A4)
    story = []
    for line in md_path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            story.append(Spacer(1, 8))
            continue
        style = styles["Heading1"] if line.startswith("# ") else (
            styles["Heading2"] if line.startswith("## ") else styles["BodyText"]
        )
        text = line.lstrip("#").strip()
        story.append(Paragraph(text, style))
    doc.build(story)


def main() -> None:
    try:
        import reportlab  # noqa: F401
    except ImportError:
        print(
            "reportlab is not installed — skipping PDF rendering. "
            "The .md files in data/documents/ are already usable by the RAG "
            "pipeline. Run `pip install reportlab` to also get PDFs.",
            file=sys.stderr,
        )
        return

    md_files = list(DOCS_DIR.glob("*.md"))
    if not md_files:
        print("No .md files found — run data/synthetic/generate_all.py first.")
        return

    for md_path in md_files:
        pdf_path = md_path.with_suffix(".pdf")
        render_pdf(md_path, pdf_path)
        print(f"Rendered {pdf_path}")


if __name__ == "__main__":
    main()
