# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x12\x61rgus.inference.v1\"\xc4\x01\n\x0ePredictRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x15\n\rmodel_version\x18\x02 \x01(\t\x12\x12\n\nrequest_id\x18\x03 \x01(\t\x12\x42\n\x08\x66\x65\x61tures\x18\x04 \x03(\x0b\x32\x30.argus.inference.v1.PredictRequest.FeaturesEntry\x1a/\n\rFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\x82\x01\n\x0fPredictResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x01\x12\r\n\x05label\x18\x04 \x01(\t\x12\x11\n\thigh_risk\x18\x05 \x01(\x08\x12\x18\n\x10\x65xplanation_json\x18\x06 \x01(\t\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xb7\x01\n\x10InferenceService\x12R\n\x07Predict\x12\".argus.inference.v1.PredictRequest\x1a#.argus.inference.v1.PredictResponse\x12O\n\x06Health\x12!.argus.inference.v1.HealthRequest\x1a\".argus.inference.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST_FEATURESENTRY']._loaded_options = None
  _globals['_PREDICTREQUEST_FEATURESENTRY']._serialized_options = b'8\001'
  _globals['_PREDICTREQUEST']._serialized_start=40
  _globals['_PREDICTREQUEST']._serialized_end=236
  _globals['_PREDICTREQUEST_FEATURESENTRY']._serialized_start=189
  _globals['_PREDICTREQUEST_FEATURESENTRY']._serialized_end=236
  _globals['_PREDICTRESPONSE']._serialized_start=239
  _globals['_PREDICTRESPONSE']._serialized_end=369
  _globals['_HEALTHREQUEST']._serialized_start=371
  _globals['_HEALTHREQUEST']._serialized_end=386
  _globals['_HEALTHRESPONSE']._serialized_start=388
  _globals['_HEALTHRESPONSE']._serialized_end=420
  _globals['_INFERENCESERVICE']._serialized_start=423
  _globals['_INFERENCESERVICE']._serialized_end=606
# @@protoc_insertion_point(module_scope)
